
a=int(input("enter data:"))
b=int(input("enter data:"))
print(f"The addition of{a}+{b} is:",a+b)
print(f"The subtraction of{a}-{b} is:",a-b)
print(f"The multiplication of{a}*{b} is:",a*b)
print(f"The devision of{a}/{b} is:",a/b)
print(f"The devision of{a}//{b} is:",a//b)
print(f"The modulus of{a}%{b} is:",a%b)
print(f"The power of{a}**{b} is:",a**b)
